language: go

sudo: false
dist: trusty

branches:
  only:
  - master

go:
- 1.15.x

before_install:
- make deps-ci

script:
- make test-ci

after_success:
- bash <(curl -s "https://codecov.io/bash")	
- $HOME/gopath/bin/goveralls -coverprofile=coverage.txt -service=travis-ci -repotoken $COVERALLS_TOKEN